import type { Metadata } from 'next'

import { Noto_Serif_TC as FontSans, Noto_Sans_TC as FontSerif } from 'next/font/google'
import { ThemeProvider } from 'next-themes'

import { cn } from '@/lib/utils'

import '@/styles/globals.css'

const fontSerif = FontSerif({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-serif',
})

const fontSans = FontSans({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="zh-Hant-TW" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable,
          fontSerif.variable,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
